import Head from "next/head";
import Image from "next/image";
import Lives from "../components/Lives";
import MatchWords from "../components/matchWords/MatchWords";
import { Counter } from "../features/counter/Counter";

import { setInitialState } from "../features/matchWords/matchWordsSlice";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import BackgroundImage from "../components/BackgroundImage";

const phraseArray = ["I", "brush", "my", "teeth."]; //TODO Put this somewhere else  || the phrase could come from an api request

export default function Home() {
  const dispatch = useDispatch();

  const initialPhrase = useSelector((state) => state.matchWords.initialPhrase);

  useEffect(() => {
    dispatch(
      setInitialState({
        initialPhrase: phraseArray,
        userSubmission: [],
      })
    );
  }, []);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-6 relative flex flex-col  min-h-screen">
        <div className="flex items-center gap-x-8 justify-end mb-11">
          <Lives />
          <Image src="/../public/speaker.png" height={34} width={34} />
        </div>
        <h1 className="text-4xl font-medium mb-3">Let's Practice</h1>
        <p className="text-xl">
          Put the words in the right order to make a correct sentence.
        </p>
        <div className="w-full fixed top-[55%] left-0  p-6  ">
          <MatchWords
            className=""
            wordsArray={initialPhrase.slice().sort(() => Math.random() - 0.5)}
          />{" "}
        </div>
      </main>

      <footer></footer>
      <BackgroundImage />
    </div>
  );
}
